import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('http://localhost:5000/api/v1/post')
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, [])

  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No profile data</p>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
      <div className={styles.logo}>
          <Image
              src="/logo.png"
              alt="banner"
              width={78}
              height={28}
              priority
            />
      </div>
      <div className={styles.menu}>
        <ul>
          <li><a href='#'>HOME</a></li>
          <li><a href='#'>VEHICLE</a></li>
          <li><a href='#'>LISTINGS</a></li>
          <li><a href='#'>CAR DETAILS</a></li>
          <li><a href='#'>NEWS</a></li>
          <li><a href='#'>NEWS GRID</a></li>
        </ul>
      </div>
      </div>
     
      <div className={styles.banner}>
          <Image
              src="/banner.png"
              alt="banner"
              fill
              priority
            />
      </div>
        <div className={styles.content}>
        {data.map((dataItem) => (
        <>
        <div className={styles.contentTx}>
        <h1>{dataItem.title}</h1>
        <p>
        {dataItem.body} 
         </p>
  
      </div>
        </>
      ))}
          <div className={styles.contentTx}>
            <h1>TRUSTED NAME IN AUTO-WORLD</h1>
            <p>
              Integer tortor bibendum estar faucibus gravida aliquam nulla lectus lacinia egar pulvinar matis nl risus quisque sagitis lorem acda lorem ipsum dolor sit amet consectetur adipisicing elit.
           
              Integer tortor bibendum est faucibus gravida aliquam nul lectus lacinia eget pulvinar mattis inl risus. Quisque sagittis lorem acdua er pharetral interdum quisque convallis nulla id ipsum vamus aliquam arcu arcu.
            
              Etiam imperdiet aliquam eriat volutpat mauris consecteta. Aliquam enisem pretium vitae posuere ac mats vitae arcu.
            </p>
      
          </div>
          <div className={styles.contentTx}>
            <h1>SED RT ENIM AD MINIM VENIAM QUIS NOSTRUD EXERCITATION</h1>
            <p>
            Wliquam sit amet urna sed vel nullam semper aiber vestibulum fringilla orem ipsum dolor sit amet consectetur adipisicing elit sed don eiusmod tempor incididunt ut labore et dolore magna aliquaa enimd ad minim veniam quis nostrud.
            </p>
           
          </div>
        </div>
     
    </>
  )
}
